import 'dotenv/config';
import { format, subDays } from 'date-fns';
import axios from 'axios';
import { collectForService } from '../collectors/azureCollector.js';
import * as gitSync from '../collectors/gitSync.js';
import { analyze } from '../agents/claudeAgent.js';

/**
 * Full pipeline for a single service:
 *   1. Collect test results from Azure DevOps
 *   2. Clone / pull the automation + service repos
 *   3. Create a fix-branch worktree (if service.agent.createFixBranch)
 *   4. Run Claude Code analysis
 *   5. Commit + push + open PR (if fixes were made)
 *   6. Clean up worktree
 *
 * @param {import('../../services/base.schema.js').Service} service
 * @param {Date} date
 * @returns {Promise<ServiceResult>}
 */
export async function runService(service, date) {
  const dateStr = format(subDays(date, 1), 'yyyy-MM-dd');
  const fixBranch = `fix/${service.id}-${dateStr}`;
  let worktreePath = null;

  console.log(`\n[runService] ▶ ${service.displayName}`);

  // ── 1. Collect test results ────────────────────────────────────────────────
  const testResults = await collectForService(service, date);

  // ── 2. Sync repos ──────────────────────────────────────────────────────────
  const automationBase = await gitSync.ensureRepo(service.repos.automation);
  const serviceBase = service.repos.service
    ? await gitSync.ensureRepo(service.repos.service)
    : null;

  // ── 3. Worktree for fix-branch runs ────────────────────────────────────────
  let analysisCwd = automationBase;
  let useWorktreeIsolation = true; // let the SDK handle isolation for read-only runs

  if (service.agent.createFixBranch) {
    const worktreeId = `${service.id}-${dateStr}`;
    worktreePath = await gitSync.createWorktree(
      service.repos.automation,
      worktreeId,
      fixBranch,
    );
    analysisCwd = worktreePath;
    useWorktreeIsolation = false; // we own the worktree; don't double-wrap
  }

  // ── 4. Claude analysis ─────────────────────────────────────────────────────
  const analysis = await analyze(
    service,
    testResults,
    { automation: analysisCwd, service: serviceBase, useWorktreeIsolation },
    date,
  );

  // ── 5. Commit + push + PR ──────────────────────────────────────────────────
  let fixBranchUrl = null;
  let prUrl = null;

  if (service.agent.createFixBranch && worktreePath) {
    const pushed = await gitSync.commitAndPush(
      worktreePath,
      fixBranch,
      `fix: auto-fix test failures for ${service.displayName} [${dateStr}]\n\nGenerated by morning-report-agent`,
    );

    if (pushed) {
      fixBranchUrl = buildBranchUrl(service, fixBranch);
      prUrl = await openPullRequest(service, fixBranch, dateStr).catch(err => {
        console.warn(`[runService] PR creation failed for ${service.id}: ${err.message}`);
        return null;
      });
    }

    await gitSync.removeWorktree(service.repos.automation, worktreePath);
  }

  console.log(`[runService] ■ ${service.displayName} — ${analysis.status}`);

  return {
    serviceId: service.id,
    displayName: service.displayName,
    status: analysis.status,
    passed: analysis.passed ?? 0,
    total: analysis.total ?? 0,
    failures: analysis.failures ?? [],
    confidence: analysis.confidence ?? 'LOW',
    fixBranchUrl,
    prUrl,
  };
}

// ─── Azure DevOps PR creation ─────────────────────────────────────────────────

async function openPullRequest(service, fixBranch, dateStr) {
  const orgName = process.env.AZURE_DEVOPS_ORG_NAME;
  const project = service.pipeline.project ?? process.env.AZURE_DEVOPS_PROJECT;
  const repoName = service.repos.automation.url.split('/').pop();
  const orgUrl = `https://dev.azure.com/${orgName}`;

  const apiUrl = `${orgUrl}/${project}/_apis/git/repositories/${repoName}/pullrequests?api-version=7.1`;

  const body = {
    title: `fix: auto-fix test failures — ${service.displayName} [${dateStr}]`,
    sourceRefName: `refs/heads/${fixBranch}`,
    targetRefName: `refs/heads/${service.repos.automation.branch ?? 'main'}`,
    description: [
      `Automated fix generated by morning-report-agent on ${dateStr}.`,
      '',
      'Review the changes carefully before merging — automated fixes may need',
      'adjustment for edge cases not covered by the failing tests.',
    ].join('\n'),
  };

  const response = await axios.post(apiUrl, body, {
    auth: { username: '', password: process.env.ADO_MCP_AUTH_TOKEN },
  });

  const pr = response.data;
  const prWebUrl = `${orgUrl}/${project}/_git/${repoName}/pullrequest/${pr.pullRequestId}`;
  console.log(`[runService] PR opened: ${prWebUrl}`);
  return prWebUrl;
}

function buildBranchUrl(service, fixBranch) {
  const orgName = process.env.AZURE_DEVOPS_ORG_NAME;
  const project = service.pipeline.project ?? process.env.AZURE_DEVOPS_PROJECT;
  const repoName = service.repos.automation.url.split('/').pop();
  return `https://dev.azure.com/${orgName}/${project}/_git/${repoName}?version=GB${encodeURIComponent(fixBranch)}`;
}

/**
 * @typedef {object} ServiceResult
 * @property {string}   serviceId
 * @property {string}   displayName
 * @property {string}   status         - 'PASSED' | 'FAILED' | 'ERROR'
 * @property {number}   passed
 * @property {number}   total
 * @property {object[]} failures
 * @property {string}   confidence
 * @property {string|null} fixBranchUrl
 * @property {string|null} prUrl
 */
